theme: jekyll-theme-minimal
source: .
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
destination: _site
exclude:
- Gemfile
- Gemfile.lock
include: ['.htaccess']